import Head from "next/head";
import { Navbar } from "@/components/navbar/Navbar";
import { Hero } from "@/components/Hero";
import { AboutMe } from "@/components/AboutMe";
import { Skills } from "@/components/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Joel Wong</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <AboutMe />
        <Skills />
      </main>
    </>
  );
}
